### ISSUE TITLE
when will come next episode about memory mapped io?

### ISSUE THREAD

**Issue by furesoft** [LowLevelJavaScript/16-Bit-Virtual-Machine#3]
hi, i am writing my own vm, but in csharp. i like your series but when will the next episode about memory mapped io be available?

**Comment by francisrstokes** [comment]
That sounds really cool - can you share a link to the project?

The memory mapping episode is next up, and will be out in the next few weeks.

**Comment by furesoft** [comment]
my vm: https://github.com/furesoft/RegVM
already implemented: stack, registers, port mapped io, memory mapped io, ...
